# Changes here will be overwritten by Copier
_commit: v0.4.0
_src_path: https://github.com/gookeryoung/coopie
author_email: gooker_young@qq.com
author_name: gooker_young
coverage_fail_under: 95
description: 基于 [copier](https://copier.readthedocs.io/) 的通用 Python 项目模板。
initial_version: 0.1.8
license: MIT
max_python_version: '3.14'
min_python_version: '3.8'
package_name: coopie
project_name: coopie
project_type: library
use_cicd: true
use_cli: true
use_docker: false
use_docs: true
use_domestic_mirrors: true
use_tox: true

